---
# shared Variables for UCS instances

# General connection variables
ansible_port: 22
ansible_user: root
ansible_password: "{{ vault_ucs_password }}"
ansible_python_interpreter: /usr/bin/python3

# For each of these Subtrees, the following ACL is written:
# access to * by dn.subtree="{{item}}" disclose stop
ldap_disable_read_access:
  - "cn=users,dc={{ucs_org_name}},dc=intranet"
  - "cn=self registered users,dc={{ucs_org_name}},dc=intranet"
